### ISSUE TITLE
Any chance for Spout Output as well from OBS?

### ISSUE THREAD

**Issue by ToxMox** [Off-World-Live/obs-spout2-source-plugin#11]
Thanks for the great plugin! Any plans to add a Spout output filter by any chance? Would be wonderful :)

**Comment by facingtomorrow** [comment]
Spout out (similar to how the NDI or virtual webcam) would be amazing!

**Comment by facingtomorrow** [comment]
@campbellwmorgan I'd love to be involved, but haven't done any OBS dev before

**Comment by lou12331** [comment]
Just for reminder.
OBS 26.0 release, OBS support virtual camera now.
It just like Spout output.

**Comment by facingtomorrow** [comment]
@lou12331 The new built-in virtual camera is nice to see, tho it doesn't have any filter output options.  Some reason it also just causes TouchDesigner to hang, so for webcam purposes, the plugin is still far superior.
Spout is still preferred in terms of quality/latency and alpha support.

Nevertheless, I do plan on picking up this task again in the next couple weeks.

**Comment by clantogw** [comment]
i have nothing to contribute just wanted to drop by and say i would be very happy to use spout instead of NDI or obs-cam as both solutions arent ideal for my application

**Comment by febox6** [comment]
+1 for spout output, it would be awesome!

**Comment by PedroNan** [comment]
I join the previous comments! An OBS output plugin from Spout would be great. In my particular case, I need to import the OBS video output into Touchdesigner and with the virtual camera it doesn't work.

**Comment by campbellwmorgan** [comment]
Just mentioned on #14 that we are beginning work on this internally. @facingtomorrow did you ever manage to start work on this?

**Comment by facingtomorrow** [comment]
I did end up creating the plugin aspect, and that seems to be mostly functional.  However, I can't quite get the graphics-side of things, so it's just a black output at the moment.

**Comment by campbellwmorgan** [comment]
Update: we think we've got the code done, but are going to do some internal QA on it before releasing a beta of it next week. Will keep you all posted

**Comment by facingtomorrow** [comment]
Had an issue with the plugin installer not being able to write files, but ran it on another computer and copied over the files.  Seems to work well so far!
Are there plans to make a filter output as well?

**Comment by clantogw** [comment]
Indeed! I have been following along here and excited to see the progress but filter output is crucial to my application if anyone with the know how can figure it out. I will continue to follow the project for updates. Thank you

**Comment by ToxMox** [comment]
I'm glad to see progress on this! I will also keep following until hopefully it gets added to the output for individual sources and scenes like you can do with the NDI plugin.

**Comment by campbellwmorgan** [comment]
Hey, @febox6 @ToxMox @clantogw yes we're definitely going to make a filter. Hoping to get on to this in the coming weeks!

**Comment by febox6** [comment]
Any news on this?

**Comment by campbellwmorgan** [comment]
@febox6 yes it was released nearly two weeks ago. Download the latest release to use!
