### ISSUE TITLE
Bounty on spout output

### ISSUE THREAD

**Issue by edstoica** [Off-World-Live/obs-spout2-source-plugin#14]
Dear friends. We like to support the development of a spout output feature with a 500eur bounty.

We are a unreal developer team. Last project was "ColoryVR" which is released on steam.

Any response would be helpful.

Best regards, ed.
www.lucidlayers.com

**Comment by nbtm-sh** [comment]
Hi, Just a few questions

* What exactly do you want to "output"?
* Where will the output be routed to?
* What is the use case for this?

**Comment by MadlyFX** [comment]
I'm not OP, but I'd also like to see spout output with the following features:

- Ideally I'd like to be able to define a region of a window or desktop to output
- It wouldn't be routed anywhere in particular, just a standard shared texture spout output. We would need to be able to define a name for the source.
- This would be useful for capturing desktop or windows and sending them into media solutions like VVVV, LightAct, Unreal, etc.

https://spoutlibrary-site.netlify.app/#File:SpoutLibrary.cpp:SendFbo

**Comment by nbtm-sh** [comment]
I believe it's certainly possible. My friend wanted it to be able to simply output the entire OBS scene like a Windowed Projection even when the scene wasn't active.

Is it something along the lines of that?

**Comment by febox6** [comment]
I think the NDI plugin is a good example of what is needed. 
Basically there's a main output for the current view and a filter that can output a single scene.

https://obsproject.com/forum/resources/obs-ndi-newtek-ndi%E2%84%A2-integration-into-obs-studio.528/

"Three integrations are currently available:
- ~~NDI Source: add NDI Sources into OBS like any traditional source~~ _(this one we already have)_
- NDI Output: transmit the main program view over NDI
- NDI Filter: a special OBS filter that outputs its parent OBS source to NDI (audio works only with video capture sources, media sources and VLC sources)"

**Comment by edstoica** [comment]
Hello,

thank you for the comments,

but I am talking about a "SPOUT - Output" Plugin.
So we can send the OBS output to an other Programm via SPOUT (not NDI)

This would be helpfull for programms that do not support NDI, but SPOUT.

**Comment by campbellwmorgan** [comment]
Hi everybody, Just to let you know that we have decided to start working on this at Off World Live so we should have some update over the next week or so. As I mentioned before, if there are any C / C++ developers out there who want to participate by either doing code review or, more generally people who might want to test this, keep a keen eye on the thread on #11

**Comment by febox6** [comment]
@campbellwmorgan that's great news, thank you very much!

@edstoica I just mentioned the NDI plugin as an example of the functions needed in the SPOUT output plugin.

**Comment by edstoica** [comment]
@febox6 yes, I see now clearly. sorry for misunderstanding and reading not carefully ;)

**Comment by MadlyFX** [comment]
> 
> 
> Hi everybody, Just to let you know that we have decided to start working on this at Off World Live so we should have some update over the next week or so. As I mentioned before, if there are any C / C++ developers out there who want to participate by either doing code review or, more generally people who might want to test this, keep a keen eye on the thread on #11

Hello! Just wanted to complicate your life further and request if there's a way to allocate _multiple_ simultaneous NDI outputs.
Specifically, in my situation, I'd like to be able to send two different regions of the screen as two different NDI feeds.

If this doesn't jive with what you're already doing, or if it's simply not possible, feel free to ignore this. But more flexibility is always good!

**Comment by campbellwmorgan** [comment]
The release is here : https://github.com/Off-World-Live/obs-spout2-source-plugin/releases/tag/v1.0_beta
