### ISSUE TITLE
OBS 有收到讯号但显示不出视频

### ISSUE THREAD

**Issue by Phaytxin** [Off-World-Live/obs-spout2-source-plugin#16]
我也是个新人，我是在研究虚拟摄影这方面。客服也有帮助我了但也没什么效果。他的问题就是ue发出了讯号检测得到，但问题出在obs，obs检测得到讯号但显示不出视频
laptop msi gf63
CPU - i5-9300
ram - 20GB
GPU - Nvidia GTX 1650 Titan Max - Q
window 10 home
version - 20H2

![unknown 1](https://user-images.githubusercontent.com/72443789/108205338-e8699f00-715f-11eb-81fd-83190f37223a.png)
![unknown](https://user-images.githubusercontent.com/72443789/108205390-f7505180-715f-11eb-9412-b32df4a99b8e.png)
![unknown](https://user-images.githubusercontent.com/72443789/108205440-0a632180-7160-11eb-8507-736176b8b421.png)

**Comment by campbellwmorgan** [comment]
hi @Phaytxin thanks for submitting the report. Could you give a bit of background on this. What machine are you using is it a laptop with dual GPUs.

This looks to me like OBS Studio is not running on the correct GPU.

Please could you follow the OBS guide here https://obsproject.com/wiki/Laptop-Troubleshooting and then get back to us if it continues to be an issue

**Comment by Phaytxin** [comment]
There is all run at GTX 1650 same GPU

**Comment by campbellwmorgan** [comment]
Could you also try this and see if it works https://obsproject.com/wiki/Laptop-GPU-Selection-Nvidia

**Comment by Phaytxin** [comment]
> Could you also try this and see if it works https://obsproject.com/wiki/Laptop-GPU-Selection-Nvidia

i already teast is still same

**Comment by campbellwmorgan** [comment]
Would you mind uploading your OBS logs when you get the black screen. To find your logs go to `Help`->`Log Files` -> `View current log` and attach that here. Thanks

**Comment by campbellwmorgan** [comment]
Also, is your unreal scene in DirectX11 or Directx 12?

**Comment by Phaytxin** [comment]
> Also, is your unreal scene in DirectX11 or Directx 12?

i just see is X11
How to change it?

**Comment by Phaytxin** [comment]
> Would you mind uploading your OBS logs when you get the black screen. To find your logs go to `Help`->`Log Files` -> `View current log` and attach that here. Thanks

where can find it?
i cant find

**Comment by campbellwmorgan** [comment]
I think it's in this menu 
![image](https://user-images.githubusercontent.com/1377367/108349512-f577a400-71da-11eb-8b4f-599bbfca4f39.png) 
It's the menu that has more options inside it..

**Comment by campbellwmorgan** [comment]
Did you have any further luck with this?

**Comment by campbellwmorgan** [comment]
Closing - no feedback
