### ISSUE TITLE
Spout Output - Alpha Channel

### ISSUE THREAD

**Issue by nuclearsugar** [Off-World-Live/obs-spout2-source-plugin#23]
Regarding the new Spout Output that is currently in beta, would it be possible to output the alpha channel? Currently any opacity information is just flattened to black. But I'm not sure if this is a limitation of OBS itself, or something that can be supported in this plugin.

Much respect! This plugin has been useful in so many ways. Very excited to see the Spout Output functionality being added.

**Comment by campbellwmorgan** [comment]
Glad you like the plugin! This is something that we looked into when making it and as far as it seems, getting the alpha is not possible from the OBS API as an Output. However, we are planning to add a spout filter which will be able to get access to the alpha which should be what you need.

Hope the work on the filter will happen in the coming weeks as the hard part was doing the output :)

**Comment by nuclearsugar** [comment]
Just wanted to say thank you for adding the Spout Filter with support for alpha. Putting it to good use already! Here is a demo - https://vimeo.com/599028390
