### ISSUE TITLE
Installer does not detect correct obs-studio directory

### ISSUE THREAD

**Issue by campbellwmorgan** [Off-World-Live/obs-spout2-source-plugin#9]
* OBS Studio is sometimes installed to `C:\Program Files\obs-studio` instead of `C:\Program Files (x86)\obs-studio`.
* The installer has no check for whether OBS Studio actually exists in that directory so often installs the plugin to an empty `obs-studio` directory

## Fix

* Check whether the directory exists and contains an OBS Studio binary

### Stretch Goal

* Automatically detect OBS Studio location by checking binary in both `Program Files` and `Program Files (x86)`

**Comment by shugen002** [comment]
I notice that some obs plugin are using Inno Setup Script ,and most of them support read OBS location from registry . 
And I have already tried to use it make a installer in https://github.com/shugen002/obs-spout2-source-plugin/releases/download/v0.3/setup.exe , (Just Try , didn;t commit).
should we switch to use Inno Setup Script ? or learn from their detect way ?

**Comment by campbellwmorgan** [comment]
Hi @shugen002 really sorry for being so slow to get back to you (I've been busy helping some people stream a virtual club night in 360 video!). I have no problems at all about migrating installers. I just chose this one because it's something I found somewhere in the OBS source. I'm pretty sure you can also get the registry key with NSIS. Could you share the line in your inno setup script that gets the registry?

Very happy to use your setup script instead if easy.

**Comment by shugen002** [comment]
I also copy from other OBS source.
```
function GetDirName(Value: string): string;
var
	InstallPath: string;
begin
	// initialize default path, which will be returned when the following registry
	// key queries fail due to missing keys or for some different reason
	Result := '{pf}\obs-studio';
	// query the first registry value; if this succeeds, return the obtained value
	if RegQueryStringValue(HKLM32, 'SOFTWARE\OBS Studio', '', InstallPath) then
		Result := InstallPath
end;
```

**Comment by marijneken** [comment]
I found this issue, after I installed and found out myself that it was installed in the wrong directory. Since this is a 64-bit plugin, maybe at least make it the default to install to `C:\Program Files\obs-studio`, since that is the default location for all 64-bit software in Windows (10).

**Comment by campbellwmorgan** [comment]
Hi @marijneken @shugen002 sorry for letting this slip behind. I've been very busy. Will try and fix this today and if i can't fall back to x86-64 path as you suggest.

**Comment by campbellwmorgan** [comment]
@marijneken see  https://github.com/Off-World-Live/obs-spout2-source-plugin/releases/tag/v0.4 for a fixed installer

**Comment by marijneken** [comment]
Thanks for fixing.
